pages:
  - Home: index.md
  - Tech Stack:
    - Overview: tech/stack.md
    - Python: tech/python-anatomy.md
  - Stash: stash.md

site_name: Codecats CV
repo_url: https://github.com/obestwalter/codecats-cv
strict: True
theme: material
extra:
  logo: _static/logo.png
  author:
    github: obestwalter
    twitter: obestwalter
extra_css:
  - _static/extra.css
markdown_extensions:
    - admonition
    - toc:
        permalink: True #¶
